IS_ATTRIBUTE = 0x1
IS_CMD_FIELD = 0x2
IS_COMMAND_RECEPTION = 0x4
IS_OTHERS = 0x8

HOLD = 0x1
NOT_HOLD = 0x2
NO_CLEAR_RELATIONSHIP = 0x3

IS_ZBEE = 0
IS_ZWAVE = 1

API_KEY = 'Your-API-key-here'
LLM_MODEL = "GPT-3.5-Turbo"